apiVersion: v1
kind: Service
metadata:
  name: aqua-exec-detection
  labels:
    app: aqua-exec-detection
spec:
  ports:
    - name: web
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: aqua-exec-detection
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-exec-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-exec-detection
  template:
    metadata:
      labels:
        app: aqua-exec-detection
    spec:
      containers:
        - name: aqua-exec-detection
          image: bkmorrow/aqua-exec-detection:latest
          imagePullPolicy: Always
          env:
            - name: AQUA_URL
              value: "http(s)://aquaurl"
            - name: AQUA_USER
              value: "aqua-user"
            - name: AQUA_PASSWORD
              value: "aqua-password"
